/**
 * Contract config — re-exports the generated ABI with the runtime address from env.
 *
 * The ABI is auto-generated by @wagmi/cli from compiled Hardhat artifacts.
 * Run `npm run generate` to regenerate after contract changes.
 */

import { counterAbi } from '@/generated'
import { env } from '@/lib/env'
import type { Address } from 'viem'

export { counterAbi }

export const counterConfig = {
  address: (env.VITE_CONTRACT_ADDRESS || undefined) as Address | undefined,
  abi: counterAbi,
} as const
