/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ExamplesFormRouteImport } from './routes/examples/form'
import { Route as ExamplesContractRouteImport } from './routes/examples/contract'
import { Route as ExamplesAuthRouteImport } from './routes/examples/auth'

const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ExamplesFormRoute = ExamplesFormRouteImport.update({
  id: '/examples/form',
  path: '/examples/form',
  getParentRoute: () => rootRouteImport,
} as any)
const ExamplesContractRoute = ExamplesContractRouteImport.update({
  id: '/examples/contract',
  path: '/examples/contract',
  getParentRoute: () => rootRouteImport,
} as any)
const ExamplesAuthRoute = ExamplesAuthRouteImport.update({
  id: '/examples/auth',
  path: '/examples/auth',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/examples/auth': typeof ExamplesAuthRoute
  '/examples/contract': typeof ExamplesContractRoute
  '/examples/form': typeof ExamplesFormRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/examples/auth': typeof ExamplesAuthRoute
  '/examples/contract': typeof ExamplesContractRoute
  '/examples/form': typeof ExamplesFormRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/examples/auth': typeof ExamplesAuthRoute
  '/examples/contract': typeof ExamplesContractRoute
  '/examples/form': typeof ExamplesFormRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/about' | '/examples/auth' | '/examples/contract' | '/examples/form'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/about' | '/examples/auth' | '/examples/contract' | '/examples/form'
  id: '__root__' | '/' | '/about' | '/examples/auth' | '/examples/contract' | '/examples/form'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ExamplesAuthRoute: typeof ExamplesAuthRoute
  ExamplesContractRoute: typeof ExamplesContractRoute
  ExamplesFormRoute: typeof ExamplesFormRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/examples/form': {
      id: '/examples/form'
      path: '/examples/form'
      fullPath: '/examples/form'
      preLoaderRoute: typeof ExamplesFormRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/examples/contract': {
      id: '/examples/contract'
      path: '/examples/contract'
      fullPath: '/examples/contract'
      preLoaderRoute: typeof ExamplesContractRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/examples/auth': {
      id: '/examples/auth'
      path: '/examples/auth'
      fullPath: '/examples/auth'
      preLoaderRoute: typeof ExamplesAuthRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ExamplesAuthRoute: ExamplesAuthRoute,
  ExamplesContractRoute: ExamplesContractRoute,
  ExamplesFormRoute: ExamplesFormRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
